### PR TITLE
LICENSE.txt

### PR DESCRIPTION
**Pull request by reckart**
License file listing the different sources and their respective licenses. Mentioning based on the statement on https://corpling.uis.georgetown.edu/gum/ that annotations in GUM inherit the license of their respective underlying texts.

### CODE REVIEW

**Comment by reckart** [comment]
@amir-zeldes Thanks! :) @Horsmann Now we can get the LICENSE file directly from the repo.

**Comment by amir-zeldes** [comment]
Thanks for thinking about it - note that the annotations themselves are all CC-BY 4.0, regardless of the underlying text, and that the annotators should be credited when the corpus is used. This is best achieved by pointing to the corpus website, which always has the most up to date list of contributors.

**Comment by reckart** [comment]
@amir-zeldes that's why it's better when the resource creators add a license file. The one I suggested was based on how I understood the description of licensing from the website - which was obviously wrong :) Thanks for integrating and improving!

**Comment by amir-zeldes** [comment]
No question, I'm not sure why I forgot to include it in the repo in this case (I see the CC-BY statement on the website wasn't versioned). The annotations are all BY, as this is the license which the annotators actually signed!

**Pull request merged**
